site_name: Ouroboros
nav:
  - Home: index.md
  - CLI Usage: usage.md
  - API Reference (importable functions and descriptions): api.md
  - Python tutorial: python_tutorial.ipynb
docs_dir: docs
plugins:
  - search
  - mkdocs-jupyter
theme:
    name: simple-blog