site_name: Ouroboros
nav:
  - Home: index.md
  - CLI Usage: usage.md
  - API Reference: api.md
  - Scanpy (python) tutorial: python_tutorial.ipynb
  - RNA velocity tutorial: velocity_in_sphere_tutorial.ipynb
  - Seurat (R) tutorial: R_tutorial.ipynb

docs_dir: docs
plugins:
  - search
  - mkdocs-jupyter
theme:
  name: alabaster

extra:
  logo: media/spinner.gif
  logo_name: true
  sidebars:
    - about
    - navigation
    - toc
    - search
  homepage_sidebars:
    - about
    - navigation
    - search
  homepage_nav: false

extra_css:
  - css/extra_css.css