[project]
name = "sc-ouroboros"
version = "1.0.5"
description = "A toolkit for investigating cell cycling dynamics in scRNA-seq"
readme = "README.md"
requires-python = ">=3.9,<3.11"
license = "MIT"
license-files = ["LICENSE"]
authors = [
  {name = "Haley MacDonald", email = "hmacdonald@bcgsc.ca"}
]

dependencies = [
  "numpy>=1.22,<1.24",
  "scipy>=1.7,<1.10",
  "pandas>=1.3.0,<2.0",
  "anndata>=0.7.5,<0.9",
  "matplotlib>=3.1.0,<3.8",
  "seaborn>=0.11.2,<0.13",
  "scikit-learn>=0.24.2,<1.3",
  "plotly>=5.18.0",
  "kaleido<1.0.0",
  "nbformat",
  "kneed",
  "requests",
  "tensorflow>=2.8,<2.12",
  "tensorflow-probability>=0.18,<0.19"
]


[project.urls]
Homepage = "https://github.com/haleymac/Ouroboros"

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project.scripts]
ouroboros = "ouroboros.main:main"

[tool.setuptools.package-data]
"ouroboros" = ["data/*", "data/model/*"]
