[metadata]
name = ouroboros
version = 0.1.0
description = A toolkit for investigating cell cycling dynamics in scRNA-seq
author = Haley MacDonald
author_email = hmacdonald@bcgsc.ca
license = MIT

[options]
packages = find:
python_requires = ==3.6.*

[options.entry_points]
console_scripts =
    ouroboros = Ouroboros.main:main
